### ISSUE TITLE
What do we want on our hackMGM website?

### ISSUE THREAD

**Issue by jacquelineIO** [HackMGM/hackmgm-notes#3]
**Montgomery Brigade Website:** 

**Current site:**
https://hackmgm.org/

**Prototype for a new site:**
https://hidden-inlet-58935.herokuapp.com/
A lot missing from this site, and is currently mostly a static site less some JS for the meetup information and twitter information.

After putting together this memo, the GitHub Pages look nice and we can easily fork and change one of the existing Brigade sites that are in use. KC and Oakland are 2 that I've found that seem to be GitHub Pages. 

What to include in the initial hackMGM website? Add comments to highlight wanted features.
Are we doing any mock draw ups or leaving it completely up to whoever creates the site?

A few things that come to mind are:

- Upcoming events
- github link
- current projects (github link to current projects?)
- opendata montgomeryal information 
- form to suggest new projects
- "in the news" and relevant articles
- hackMGM/Brigade goals/vision/purpose
- Request for speakers
- Link to github issue for site, so that anyone can report an issue on the site
- Contact us / how to contact the brigade
- Our collaborations: slack, meetup.com, FB group
- Sponsors
- Blog/newsletter
     -- Allow comments?
- mail list subscription? is meetup.com good enough or do we also want mail chimp or something like that? If we add a blog, then we should probably add mailchimp or contact contact

**CfA endorsed templates:**
- Brigade Website Template
- **Classic Brigade Site** - A **Github Pages** hosted simple site originally by Code for Hampton Roads.
     -- https://github.com/sfbrigade/sfbrigade.github.io   (no longer in use)
     -- http://codeforsanfrancisco.org/  (They have actually moved away from github pages)
     -- https://github.com/brigadehub/brigadehub (used by Code for SF)
     -- http://code4hr.org/  (I think this is using github pages)
     -- http://brigade.openoakland.org/ (I think this is using github pages)
- **Laddr** - A really powerful Brigade management platform. Built by Code for Philly.
    -- example: philly, http://codefordurham.com/ 
    -- requires emergence, explained in the readme but linking post here about it: https://www.reddit.com/r/PHP/comments/u9ve9/i_think_its_about_time_i_introduced_rphp_to/
  
	
**Free mockup tool (For Brigades)**
myBalsamiq - Donated access to this easy prototyping tool.

**List of other brigade sites:**

**Birmingham:**
http://brigade.codeforamerica.org/brigade/Code-for-Birmingham/
http://www.codeforbirmingham.org/

**Boston:**
Uses hackpad for collaboration, interesting, https://codeforboston.hackpad.com/

**Colorado:**
http://brigade.codeforamerica.org/brigade/Code-for-Boulder/
http://www.codeforboulder.org/
Theme
Wordpress WPExplorer WPEX theme free.
https://github.com/wpexplorer/wpex-gopress
http://www.wpexplorer.com/gopress-wordpress-theme/

**NYC**
http://brigade.codeforamerica.org/brigade/Beta-NYC/
https://beta.nyc/   very cool 
Theme
https://sketchthemes.com/premium-themes/multipurpose-business-wordpress-theme-for-corporate-agency/
https://wordpress.org/themes/invert-lite/

**Extras:** 
Might be cool to add to site 

**Code for America TED Talk**
http://www.ted.com/talks/jennifer_pahlka_coding_a_better_government?language=en

**Highlight Montgomery Videos:**

Visiting Montgomery
https://www.youtube.com/watch?v=6xGb9JlQDXs

Montgomery Alabama is the Capital of Dreams
https://www.youtube.com/watch?v=4pHBO83jxyA

Visit Montgomery Ala. - Capital Cool
https://www.youtube.com/watch?v=L-E2gUwnaaE

City of Montgomery featured on Star 64
https://www.youtube.com/watch?v=wtozO9MMjzo

Capital of Dreams
https://www.youtube.com/watch?v=GYM167ChQyo

**Comment by netelysis** [comment]
Sis Flemming and CfA Crew:

So am I to gather from this correspondence that members of the 
hackMGM/CfA team will be shouldering the creation and management of the 
hackMGM.com/.org website?  Sis Flemming, are you in a position to lead 
out in this area ma'am?  If not, no worries.  I either case, please let 
me know before I expend some funding to bring this to fruition.

Thank you all for your assistance and I will await your feedback.

PS BTW, I think that the framework for the prototype that you have 
created is HOT and What's Up!!

-- 
Boyd Stephens
Network Engineering Division

Netelysis, LLC
PO Box 230546
Montgomery, AL 36123

tel.    334.213.1128
web.    www.netelysis.com
email.  bstephens@netelysis.com

The information contained in this communication is confidential, may be subject to legal privileges, may constitute inside information, and is intended only for the use of the addressee. It is the property of Netelysis or its relevant affiliate. Unauthorized use, disclosure or copying of this communication or any part thereof is strictly prohibited and may be unlawful. If you have received this communication in error, please notify Netelysis immediately by return e-mail and destroy this communication and all copies thereof, including all attachments.

**Comment by jacquelineIO** [comment]
@netelysis I can lead out for the website. I'm not exactly sure what that entails but we can chat more about that. 

As far as creation and management, I don't know what we have to work with here. I was hoping to get initial feedback from the group and mostly the small group that indicated we wanted to meet to come up with some ideas/options around some open items that we had for the group. So I wanted to help push this effort along and put some ideas out there for the website.

What is our server situation? I'd imagine we'd need to know this anyway to work with future projects (maybe maybenot?). 

But I can definitely work to have an initial site. I figure no matter where we start, it would be a living growing thing, and an easy opportunity for someone else to pick up and add/change if they so please and everyone is in agreement. The site I'm showing is mostly a static site and would eventually want to be a GitHub Page or some other web framework supported site.

**Comment by jacquelineIO** [comment]
I'm going to close this out, since the website is up and mostly because this item is on the wrong github repo. Going to make a reference in the hackmgm repo.
